name: Test standards compliance
on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  compliance:
    uses: courtois-neuromod/actions-datasets/.github/workflows/compliance.yml@main
